from __future__ import annotations

from typing import TYPE_CHECKING

from .base import Card, CardRarity, CardType, TargetType, register_card

if TYPE_CHECKING:
    from ..combat import CombatCtx


@register_card
class LuminesceCard(Card):
    """Luminesce.cs — 0-cost Token Skill (Exhaust, Retain): gain 2 Energy
    (upgrade: 3). Generated by Radiant Pearl on turn 1."""

    id = "luminesce"
    name = "Luminesce"
    card_type = CardType.SKILL
    rarity = CardRarity.TOKEN
    target_type = TargetType.SELF
    exhausts = True
    retain = True

    def _init_vars(self) -> None:
        self._energy_cost = 0
        self._energy = 2

    def _on_upgrade(self) -> None:
        self._energy += 1

    def on_play(self, ctx: CombatCtx, target_idx: int | None = None) -> None:
        from ..cmds import EnergyCmd

        EnergyCmd.gain(ctx.hooks, ctx.player, self._energy)
