from .base import Encounter, Intent, Monster, MoveType

# Overgrowth enemies (re-exported for backward compatibility and convenience)
from .overgrowth import (
    BygoneEffigy,
    Byrdonis,
    CeremonialBeast,
    CubexConstruct,
    EyeWithTeeth,
    Flyconid,
    Fogmog,
    FuzzyWurmCrawler,
    Inklet,
    KinFollower,
    KinPriest,
    Mawler,
    Nibbit,
    PhrogParasite,
    ShrinkerBeetle,
    SlitheringStrangler,
    SnappingJaxfruit,
    LeafSlimeS,
    TwigSlimeS,
    LeafSlimeM,
    TwigSlimeM,
    AxeRubyRaider,
    AssassinRubyRaider,
    BruteRubyRaider,
    CrossbowRubyRaider,
    TrackerRubyRaider,
    Vantom,
    VineShambler,
    Wriggler,
    BYGONE_EFFIGY_ELITE,
    BYRDONIS_ELITE,
    CEREMONIAL_BEAST_BOSS,
    CUBEX_CONSTRUCT_NORMAL,
    FLYCONID_NORMAL,
    FOGMOG_NORMAL,
    FUZZY_WURM_ENCOUNTER,
    INKLETS_NORMAL,
    MAWLER_NORMAL,
    NIBBITS_NORMAL,
    NIBBITS_WEAK,
    OVERGROWTH_CRAWLERS_NORMAL,
    PHROG_PARASITE_ELITE,
    RUBY_RAIDERS_NORMAL,
    SHRINKER_BEETLE_WEAK,
    SLIMES_NORMAL,
    SLIMES_WEAK,
    SLITHERING_STRANGLER_NORMAL,
    SNAPPING_JAXFRUIT_NORMAL,
    THE_KIN_BOSS,
    VANTOM_BOSS,
    VINE_SHAMBLER_NORMAL,
)

# Underdocks (Act 2) enemies
from .underdocks import (
    CalcifiedCultist,
    CorpseSlug,
    DampCultist,
    FatGremlin,
    FossilStalker,
    GasBomb,
    GremlinMerc,
    HauntedShip,
    LagavulinMatriarch,
    LivingFog,
    PhantasmalGardener,
    PunchConstruct,
    Seapunk,
    SewerClam,
    SkulkingColony,
    SludgeSpinner,
    SneakyGremlin,
    SoulFysh,
    TerrorEel,
    Toadpole,
    TwoTailedRat,
    WaterfallGiant,
    CORPSE_SLUGS_NORMAL,
    CORPSE_SLUGS_WEAK,
    CULTISTS_NORMAL,
    FOSSIL_STALKER_NORMAL,
    GREMLIN_MERC_NORMAL,
    HAUNTED_SHIP_NORMAL,
    LAGAVULIN_MATRIARCH_BOSS,
    LIVING_FOG_NORMAL,
    PHANTASMAL_GARDENERS_ELITE,
    PUNCH_CONSTRUCT_NORMAL,
    SEAPUNK_NORMAL,
    SEAPUNK_WEAK,
    SEWER_CLAM_NORMAL,
    SKULKING_COLONY_ELITE,
    SLUDGE_SPINNER_WEAK,
    SOUL_FYSH_BOSS,
    TERROR_EEL_ELITE,
    TOADPOLES_WEAK,
    TWO_TAILED_RATS_NORMAL,
    WATERFALL_GIANT_BOSS,
)

__all__ = [
    "MoveType", "Intent", "Monster", "Encounter",
    "BygoneEffigy", "Byrdonis", "CeremonialBeast", "CubexConstruct",
    "EyeWithTeeth", "Flyconid", "Fogmog", "FuzzyWurmCrawler",
    "Inklet", "KinFollower", "KinPriest", "Mawler", "Nibbit",
    "PhrogParasite", "ShrinkerBeetle", "SlitheringStrangler", "SnappingJaxfruit",
    "LeafSlimeS", "TwigSlimeS", "LeafSlimeM", "TwigSlimeM",
    "AxeRubyRaider", "AssassinRubyRaider", "BruteRubyRaider",
    "CrossbowRubyRaider", "TrackerRubyRaider",
    "Vantom", "VineShambler", "Wriggler",
    "BYGONE_EFFIGY_ELITE", "BYRDONIS_ELITE", "CEREMONIAL_BEAST_BOSS",
    "CUBEX_CONSTRUCT_NORMAL", "FLYCONID_NORMAL", "FOGMOG_NORMAL",
    "FUZZY_WURM_ENCOUNTER", "INKLETS_NORMAL", "MAWLER_NORMAL",
    "NIBBITS_NORMAL", "NIBBITS_WEAK", "OVERGROWTH_CRAWLERS_NORMAL",
    "PHROG_PARASITE_ELITE", "RUBY_RAIDERS_NORMAL", "SHRINKER_BEETLE_WEAK",
    "SLIMES_NORMAL", "SLIMES_WEAK", "SLITHERING_STRANGLER_NORMAL",
    "SNAPPING_JAXFRUIT_NORMAL", "THE_KIN_BOSS", "VANTOM_BOSS",
    "VINE_SHAMBLER_NORMAL",
    "CalcifiedCultist", "CorpseSlug", "DampCultist", "FatGremlin",
    "FossilStalker", "GasBomb", "GremlinMerc", "HauntedShip",
    "LagavulinMatriarch", "LivingFog", "PhantasmalGardener",
    "PunchConstruct", "Seapunk", "SewerClam", "SkulkingColony",
    "SludgeSpinner", "SneakyGremlin", "SoulFysh", "TerrorEel", "Toadpole",
    "TwoTailedRat", "WaterfallGiant",
    "CORPSE_SLUGS_NORMAL", "CORPSE_SLUGS_WEAK", "CULTISTS_NORMAL",
    "FOSSIL_STALKER_NORMAL", "GREMLIN_MERC_NORMAL", "HAUNTED_SHIP_NORMAL",
    "LAGAVULIN_MATRIARCH_BOSS", "LIVING_FOG_NORMAL",
    "PHANTASMAL_GARDENERS_ELITE", "PUNCH_CONSTRUCT_NORMAL",
    "SEAPUNK_NORMAL", "SEAPUNK_WEAK", "SEWER_CLAM_NORMAL",
    "SKULKING_COLONY_ELITE", "SLUDGE_SPINNER_WEAK", "SOUL_FYSH_BOSS",
    "TERROR_EEL_ELITE", "TOADPOLES_WEAK", "TWO_TAILED_RATS_NORMAL",
    "WATERFALL_GIANT_BOSS",
]
