from .base import Encounter, Intent, Monster, MoveType

# Overgrowth enemies (re-exported for backward compatibility and convenience)
from .overgrowth import (
    BygoneEffigy,
    Byrdonis,
    CeremonialBeast,
    CubexConstruct,
    EyeWithTeeth,
    Flyconid,
    Fogmog,
    FuzzyWurmCrawler,
    Inklet,
    KinFollower,
    KinPriest,
    Mawler,
    Nibbit,
    PhrogParasite,
    ShrinkerBeetle,
    SlitheringStrangler,
    SnappingJaxfruit,
    LeafSlimeS,
    TwigSlimeS,
    LeafSlimeM,
    TwigSlimeM,
    AxeRubyRaider,
    AssassinRubyRaider,
    BruteRubyRaider,
    CrossbowRubyRaider,
    TrackerRubyRaider,
    Vantom,
    VineShambler,
    Wriggler,
    BYGONE_EFFIGY_ELITE,
    BYRDONIS_ELITE,
    CEREMONIAL_BEAST_BOSS,
    CUBEX_CONSTRUCT_NORMAL,
    FLYCONID_NORMAL,
    FOGMOG_NORMAL,
    FUZZY_WURM_ENCOUNTER,
    INKLETS_NORMAL,
    MAWLER_NORMAL,
    NIBBITS_NORMAL,
    NIBBITS_WEAK,
    OVERGROWTH_CRAWLERS_NORMAL,
    PHROG_PARASITE_ELITE,
    RUBY_RAIDERS_NORMAL,
    SHRINKER_BEETLE_WEAK,
    SLIMES_NORMAL,
    SLIMES_WEAK,
    SLITHERING_STRANGLER_NORMAL,
    SNAPPING_JAXFRUIT_NORMAL,
    THE_KIN_BOSS,
    VANTOM_BOSS,
    VINE_SHAMBLER_NORMAL,
)

# Underdocks (Act 2) enemies
from .underdocks import (
    CalcifiedCultist,
    CorpseSlug,
    DampCultist,
    FatGremlin,
    FossilStalker,
    GasBomb,
    GremlinMerc,
    HauntedShip,
    LagavulinMatriarch,
    LivingFog,
    PhantasmalGardener,
    PunchConstruct,
    Seapunk,
    SewerClam,
    SkulkingColony,
    SludgeSpinner,
    SneakyGremlin,
    SoulFysh,
    TerrorEel,
    Toadpole,
    TwoTailedRat,
    WaterfallGiant,
    CORPSE_SLUGS_NORMAL,
    CORPSE_SLUGS_WEAK,
    CULTISTS_NORMAL,
    FOSSIL_STALKER_NORMAL,
    GREMLIN_MERC_NORMAL,
    HAUNTED_SHIP_NORMAL,
    LAGAVULIN_MATRIARCH_BOSS,
    LIVING_FOG_NORMAL,
    PHANTASMAL_GARDENERS_ELITE,
    PUNCH_CONSTRUCT_NORMAL,
    SEAPUNK_NORMAL,
    SEAPUNK_WEAK,
    SEWER_CLAM_NORMAL,
    SKULKING_COLONY_ELITE,
    SLUDGE_SPINNER_WEAK,
    SOUL_FYSH_BOSS,
    TERROR_EEL_ELITE,
    TOADPOLES_WEAK,
    TWO_TAILED_RATS_NORMAL,
    WATERFALL_GIANT_BOSS,
)

# Hive (parallel Act 2) enemies
from .hive import (
    BowlbugEgg,
    BowlbugNectar,
    BowlbugRock,
    BowlbugSilk,
    Chomper,
    Crusher,
    DecimillipedeSegment,
    DecimillipedeSegmentBack,
    DecimillipedeSegmentFront,
    DecimillipedeSegmentMiddle,
    Entomancer,
    Exoskeleton,
    HunterKiller,
    InfestedPrism,
    KnowledgeDemon,
    LouseProgenitor,
    Myte,
    Ovicopter,
    Parafright,
    Rocket,
    SlumberingBeetle,
    SpinyToad,
    TheInsatiable,
    TheObscura,
    ThievingHopper,
    ToughEgg,
    Tunneler,
    BOWLBUGS_NORMAL,
    BOWLBUGS_WEAK,
    CHOMPERS_NORMAL,
    DECIMILLIPEDE_ELITE,
    ENTOMANCER_ELITE,
    EXOSKELETONS_NORMAL,
    EXOSKELETONS_WEAK,
    HUNTER_KILLER_NORMAL,
    INFESTED_PRISMS_ELITE,
    KAISER_CRAB_BOSS,
    KNOWLEDGE_DEMON_BOSS,
    LOUSE_PROGENITOR_NORMAL,
    MYTES_NORMAL,
    OVICOPTER_NORMAL,
    SLUMBERING_BEETLE_NORMAL,
    SPINY_TOAD_NORMAL,
    THE_INSATIABLE_BOSS,
    THE_OBSCURA_NORMAL,
    THIEVING_HOPPER_WEAK,
    TUNNELER_WEAK,
)

# Glory (Act 3) enemies
from .glory import (
    Aeonglass,
    Axebot,
    BattleFriendV1,
    BattleFriendV2,
    BattleFriendV3,
    DevotedSculptor,
    Fabricator,
    FrogKnight,
    GlobeHead,
    Guardbot,
    LivingShield,
    MagiKnight,
    MechaKnight,
    Noisebot,
    OwlMagistrate,
    Queen,
    ScrollOfBiting,
    SlimedBerserker,
    SoulNexus,
    SpectralKnight,
    Stabbot,
    TestSubject,
    TheForgotten,
    TheLost,
    TorchHeadAmalgam,
    TurretOperator,
    Zapbot,
    AEONGLASS_BOSS,
    AXEBOTS_NORMAL,
    CONSTRUCT_MENAGERIE_NORMAL,
    DEVOTED_SCULPTOR_WEAK,
    FABRICATOR_NORMAL,
    FROG_KNIGHT_NORMAL,
    GLOBE_HEAD_NORMAL,
    KNIGHTS_ELITE,
    MECHA_KNIGHT_ELITE,
    OWL_MAGISTRATE_NORMAL,
    QUEEN_BOSS,
    SCROLLS_OF_BITING_NORMAL,
    SCROLLS_OF_BITING_WEAK,
    SLIMED_BERSERKER_NORMAL,
    SOUL_NEXUS_ELITE,
    TEST_SUBJECT_BOSS,
    THE_LOST_AND_FORGOTTEN_NORMAL,
    TURRET_OPERATOR_WEAK,
    BATTLEWORN_DUMMY_SETTING_1,
    BATTLEWORN_DUMMY_SETTING_2,
    BATTLEWORN_DUMMY_SETTING_3,
)

__all__ = [
    "MoveType", "Intent", "Monster", "Encounter",
    "BygoneEffigy", "Byrdonis", "CeremonialBeast", "CubexConstruct",
    "EyeWithTeeth", "Flyconid", "Fogmog", "FuzzyWurmCrawler",
    "Inklet", "KinFollower", "KinPriest", "Mawler", "Nibbit",
    "PhrogParasite", "ShrinkerBeetle", "SlitheringStrangler", "SnappingJaxfruit",
    "LeafSlimeS", "TwigSlimeS", "LeafSlimeM", "TwigSlimeM",
    "AxeRubyRaider", "AssassinRubyRaider", "BruteRubyRaider",
    "CrossbowRubyRaider", "TrackerRubyRaider",
    "Vantom", "VineShambler", "Wriggler",
    "BYGONE_EFFIGY_ELITE", "BYRDONIS_ELITE", "CEREMONIAL_BEAST_BOSS",
    "CUBEX_CONSTRUCT_NORMAL", "FLYCONID_NORMAL", "FOGMOG_NORMAL",
    "FUZZY_WURM_ENCOUNTER", "INKLETS_NORMAL", "MAWLER_NORMAL",
    "NIBBITS_NORMAL", "NIBBITS_WEAK", "OVERGROWTH_CRAWLERS_NORMAL",
    "PHROG_PARASITE_ELITE", "RUBY_RAIDERS_NORMAL", "SHRINKER_BEETLE_WEAK",
    "SLIMES_NORMAL", "SLIMES_WEAK", "SLITHERING_STRANGLER_NORMAL",
    "SNAPPING_JAXFRUIT_NORMAL", "THE_KIN_BOSS", "VANTOM_BOSS",
    "VINE_SHAMBLER_NORMAL",
    "CalcifiedCultist", "CorpseSlug", "DampCultist", "FatGremlin",
    "FossilStalker", "GasBomb", "GremlinMerc", "HauntedShip",
    "LagavulinMatriarch", "LivingFog", "PhantasmalGardener",
    "PunchConstruct", "Seapunk", "SewerClam", "SkulkingColony",
    "SludgeSpinner", "SneakyGremlin", "SoulFysh", "TerrorEel", "Toadpole",
    "TwoTailedRat", "WaterfallGiant",
    "CORPSE_SLUGS_NORMAL", "CORPSE_SLUGS_WEAK", "CULTISTS_NORMAL",
    "FOSSIL_STALKER_NORMAL", "GREMLIN_MERC_NORMAL", "HAUNTED_SHIP_NORMAL",
    "LAGAVULIN_MATRIARCH_BOSS", "LIVING_FOG_NORMAL",
    "PHANTASMAL_GARDENERS_ELITE", "PUNCH_CONSTRUCT_NORMAL",
    "SEAPUNK_NORMAL", "SEAPUNK_WEAK", "SEWER_CLAM_NORMAL",
    "SKULKING_COLONY_ELITE", "SLUDGE_SPINNER_WEAK", "SOUL_FYSH_BOSS",
    "TERROR_EEL_ELITE", "TOADPOLES_WEAK", "TWO_TAILED_RATS_NORMAL",
    "WATERFALL_GIANT_BOSS",
    "BowlbugEgg", "BowlbugNectar", "BowlbugRock", "BowlbugSilk", "Chomper",
    "Crusher", "DecimillipedeSegment", "DecimillipedeSegmentBack",
    "DecimillipedeSegmentFront", "DecimillipedeSegmentMiddle", "Entomancer",
    "Exoskeleton", "HunterKiller", "InfestedPrism", "KnowledgeDemon",
    "LouseProgenitor", "Myte", "Ovicopter", "Parafright", "Rocket",
    "SlumberingBeetle", "SpinyToad", "TheInsatiable", "TheObscura",
    "ThievingHopper", "ToughEgg", "Tunneler",
    "BOWLBUGS_NORMAL", "BOWLBUGS_WEAK", "CHOMPERS_NORMAL",
    "DECIMILLIPEDE_ELITE", "ENTOMANCER_ELITE", "EXOSKELETONS_NORMAL",
    "EXOSKELETONS_WEAK", "HUNTER_KILLER_NORMAL", "INFESTED_PRISMS_ELITE",
    "KAISER_CRAB_BOSS", "KNOWLEDGE_DEMON_BOSS", "LOUSE_PROGENITOR_NORMAL",
    "MYTES_NORMAL", "OVICOPTER_NORMAL", "SLUMBERING_BEETLE_NORMAL",
    "SPINY_TOAD_NORMAL", "THE_INSATIABLE_BOSS", "THE_OBSCURA_NORMAL",
    "THIEVING_HOPPER_WEAK", "TUNNELER_WEAK",
    "BattleFriendV1", "BattleFriendV2", "BattleFriendV3",
    "BATTLEWORN_DUMMY_SETTING_1", "BATTLEWORN_DUMMY_SETTING_2",
    "BATTLEWORN_DUMMY_SETTING_3",
    "Aeonglass", "Axebot", "DevotedSculptor", "Fabricator", "FrogKnight",
    "GlobeHead", "Guardbot", "LivingShield", "MagiKnight", "MechaKnight",
    "Noisebot", "OwlMagistrate", "Queen", "ScrollOfBiting", "SlimedBerserker",
    "SoulNexus", "SpectralKnight", "Stabbot", "TestSubject", "TheForgotten",
    "TheLost", "TorchHeadAmalgam", "TurretOperator", "Zapbot",
    "AEONGLASS_BOSS", "AXEBOTS_NORMAL", "CONSTRUCT_MENAGERIE_NORMAL",
    "DEVOTED_SCULPTOR_WEAK", "FABRICATOR_NORMAL", "FROG_KNIGHT_NORMAL",
    "GLOBE_HEAD_NORMAL", "KNIGHTS_ELITE", "MECHA_KNIGHT_ELITE",
    "OWL_MAGISTRATE_NORMAL", "QUEEN_BOSS", "SCROLLS_OF_BITING_NORMAL",
    "SCROLLS_OF_BITING_WEAK", "SLIMED_BERSERKER_NORMAL", "SOUL_NEXUS_ELITE",
    "TEST_SUBJECT_BOSS", "THE_LOST_AND_FORGOTTEN_NORMAL", "TURRET_OPERATOR_WEAK",
]
